#!/bin/sh
# See https://regolith-linux.org/docs/customize/compositors/

USER_CONFIG="$HOME/.config/regolith/xcompmgr/config"
if [ -f "$USER_CONFIG" ]; then
  /bin/sh "$USER_CONFIG"
else
  /usr/bin/xcompmgr -c -t-5 -l-5 -r4.2 -o.55
fi
