#!/bin/sh
# See https://regolith-linux.org/docs/customize/compositors/

compositor_PID=$(pidof xcompmgr)
if [ ! -z "$compositor_PID" ]; then
    kill $compositor_PID
fi

USER_CONFIG="$HOME/.config/regolith2/xcompmgr/config"
if [ -f "$USER_CONFIG" ]; then
  /bin/sh "$USER_CONFIG"
else
  /usr/bin/xcompmgr -c -t-5 -l-5 -r4.2 -o.55
fi
